"""Add admin_level

Revision ID: 8753a73022bb
Revises: df0b747ac9a5
Create Date: 2019-01-11 10:13:39.909942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8753a73022bb'
down_revision = 'df0b747ac9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_admin_level'), 'user', ['admin_level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin_level'), table_name='user')
    op.drop_column('user', 'admin_level')
    # ### end Alembic commands ###
