"""empty message

Revision ID: bb16fb367f9c
Revises: 718f3ec5b2bc
Create Date: 2019-01-09 13:08:15.480790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb16fb367f9c'
down_revision = '718f3ec5b2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('last_edited_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_last_edited_timestamp'), 'post', ['last_edited_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_last_edited_timestamp'), table_name='post')
    op.drop_column('post', 'last_edited_timestamp')
    # ### end Alembic commands ###
